apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  labels:
    app: {{ include "legi-bit.name" . }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "legi-bit.name" . }}
    component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.service.nodePort }}
      protocol: TCP
