{{- /*
  Template to create AWS SecretProviderClasses dynamically
  for MongoDB and S3 services.
*/ -}}

{{- if .Values.serviceMongodb.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongodb-secrets-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.serviceMongodb.secretProvider.awsSecretName }}"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: {{ .Values.serviceMongodb.secretProvider.secretName }}
      type: Opaque
      data:
        - objectName: "{{ .Values.serviceMongodb.secretProvider.awsSecretName }}"
          key: MONGO_URI
{{- end }}

---

{{- if .Values.serviceS3.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: s3-secrets-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.serviceS3.secretProvider.awsSecretName }}"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: {{ .Values.serviceS3.secretProvider.secretName }}
      type: Opaque
      data:
        - objectName: "{{ .Values.serviceS3.secretProvider.awsSecretName }}"
          key: AWS_ACCESS_KEY_ID
        - objectName: "{{ .Values.serviceS3.secretProvider.awsSecretName }}"
          key: AWS_SECRET_ACCESS_KEY
        - objectName: "{{ .Values.serviceS3.secretProvider.awsSecretName }}"
          key: S3_BUCKET_NAME
{{- end }}