apiVersion: v1
kind: Service
metadata:
  name: ssl-redirect
  labels:
    app: {{ include "legi-bit.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: use-annotation
      port: 443
      targetPort: 443
