apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.serviceName }}
  labels:
    app: {{ include "legi-bit.name" . }}
    component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ include "legi-bit.name" . }}
    component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.port }}
