apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.serviceName }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP