global:
  imagePullPolicy: IfNotPresent
  domain: legi-bit.com

ingress:
  name: "legibit-ingress"
  tlsSecretName: legibit-tls

web:
  image:
    repository: webserver0518/legi-bit-nginx
    tag: "v0.3"
  port: 80
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

  configMapName: "web-config"
  backendUrl: "backend:9000"
  domainName: "legi-bit.com"

  serviceName: "web-service"
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: webserver0518/legi-bit-flask
    tag: "v0.3"
  port: 9000
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

  configMapName: "backend-config"
  env: "development"
  secretKey: "dfb594091faa05005d1212f4cdce9dc64a81c9ff50253210520375a9fd25a934"

  serviceName: "backend"
  service:
    type: ClusterIP
    port: 9000

serviceMongodb:
  image:
    repository: webserver0518/legi-bit-mongodb
    tag: "v0.3"
  port: 8001
  replicas: 1
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "600m"
      memory: "768Mi"

  host: "service-mongodb"

  configMapName: "service-mongodb-config"
  healthcheckPath: "/healthz"
  serverSelectionTimeout: "30000"
  socketTimeout: "10000"
  maxPoolSize: "100"

  serviceName: "service-mongodb"
  service:
    type: ClusterIP
    port: 8001

serviceS3:
  image:
    repository: webserver0518/legi-bit-s3
    tag: "v0.3"
  port: 8000
  replicas: 1
  secretName: "service-s3-secret"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

  host: "service-s3"

  configMapName: "service-s3-config"
  healthcheckPath: "/healthz"
  maxUploadSizeMb: "50"

  serviceName: "service-s3"
  service:
    type: ClusterIP
    port: 8000

redis:
  image: "redis:7-alpine"
  port: 6379
  replicas: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"

  host: "redis"
  db: "0"

  serviceName: "redis"
  service:
    type: ClusterIP
    port: 6379

https:
  email: webserver0518@gmail.com
