helm:
  parameters:
  - name: web.image.repository
    value: webserver0518/legi-bit-nginx
    forcestring: true
  - name: web.image.tag
    value: v0.59
    forcestring: true
  - name: backend.image.repository
    value: webserver0518/legi-bit-flask
    forcestring: true
  - name: backend.image.tag
    value: v0.85
    forcestring: true
  - name: mongodb.image.repository
    value: webserver0518/legi-bit-mongodb
    forcestring: true
  - name: mongodb.image.tag
    value: v0.83
    forcestring: true
  - name: s3.image.repository
    value: webserver0518/legi-bit-s3
    forcestring: true
  - name: s3.image.tag
    value: v0.83
    forcestring: true
  - name: ses.image.repository
    value: webserver0518/legi-bit-ses
    forcestring: true
  - name: ses.image.tag
    value: v0.83
    forcestring: true
