apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
type: Opaque
stringData:
  prometheus-additional.yaml: |
{{ .Files.Get "configs/prometheus/prometheus-additional.yaml" | indent 4 }}
