apiVersion: v2
name: monitoring-wrapper
description: A wrapper chart for kube-prometheus-stack with local configurations
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "66.0.0"
    repository: https://prometheus-community.github.io/helm-charts
