apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cloud-controller-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://kubernetes.github.io/cloud-provider-aws
    chart: aws-cloud-controller-manager
    targetRevision: "*"
    helm:
      values: |
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"

        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"

        hostNetwork: true

        args:
          - --v=2
          - --cloud-provider=aws
          - --configure-cloud-routes=false
          - --allocate-node-cidrs=false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
