apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/webserver0518/legi-bit-infrastructure.git
    targetRevision: main
    path: monitoring
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Automatically create the namespace if it doesn't exist
      - CreateNamespace=true
      # fix "Too long" annotation error
      - ServerSideApply=true
