apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "*"
    helm:
      parameters:
        - name: clusterName
          value: legibit
        - name: region
          value: eu-north-1
        - name: serviceAccount.create
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
